blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view,info_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'',home_view,name='home'),
    path(r'post/',include('post.urls')),
    path(r'kullanici/',include('kullanici.urls')),
    path(r'info/',info_view,name='info'),



]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

kullanici/urls.py
from django.urls import path
from .views import *
app_name='kullanici'

urlpatterns = [

    path(r'login/',login_view,name='login'),
    path(r'register/',register_view,name='register'),
    path(r'logout/',logout_view,name='logout'),



]

post/urls.py
from django.urls import path
from .views import *
app_name='post'

urlpatterns = [

    path(r'index/',post_index,name='index'),
    path(r'create/',post_create,name='create'),

    path(r'<slug>/detail/',post_detail,name='detail'),
    path(r'<slug>/update/',post_update,name='update'),
    path(r'<slug>/delete/',post_delete,name='delete'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render ,HttpResponse

def home_view(request):
    if request.user.is_authenticated:
        context={ 'isim':' ',
                  }
    else:
        context={
            'isim': 'Misafir',

        }
    return render(request,'home.html',context)
def info_view(request):
    context={
        'info':'SAKARYA ÜNİVERİSTESİ'
    }
    return render(request,'info.html',context)

templates/base.html
{%include 'header.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,inital-scale=1">
    <title>{% block title %} €NGİNEER// {% endblock %}</title>
    <link rel ="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel ="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>


{%include 'messages.html' %}


{% block body %}
{% endblock %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-md  navbar-dark bg-dark">

    <img src={% static "mainicon2.png" %} width="80" height="40" href ="{% url 'home' %}" >

    <a class="navbar-brand text-danger" href ="{% url 'home' %}">€NGİNEER//</a>


  <button class="navbar-toggler bg-success " type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar text-danger"> MENÜ </span>
  </button>
    <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link " href ="{% url 'home' %}">ANASAYFA <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href ="{% url 'post:index' %}">BLOG</a>
      </li>

        <li class="nav-item ">
        <a class="nav-link" href ="{% url 'info' %}">HAKKIMDA</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">İLETİŞİM</a>
       <li class="nav-item  ">



    </li>
    {% if request.user.is_authenticated %}
            <div class="nav-item " >
                <ul class="navbar-nav mr-auto">
                         <div class="container" >
                        <div class="col-xs-6" style="margin-bottom:5px ">
                        {% if request.user.is_authenticated %}
                         <a href=" " class="btn btn-success " aria-pressed="true">{{ user.get_username }} </a>
                        {% endif %}

                </ul>
            </div>


        <div class="nav-item " >
                <ul class="navbar-nav mr-auto">
                        <div class="container" >
                        <div class="col-xs-6" style="margin-bottom:5px ">
                        {% if request.user.is_authenticated %}
                         <a href="{% url 'kullanici:logout' %}" class="btn btn-danger " aria-pressed="true">ÇIKIŞ YAP </a>
                        {% endif %}
                         </div>
                </ul>
            </div>
            {% else %}
        <li class="nav-item ">
                    <ul class="navbar-nav mr-auto">
                        <div class="container" >
                        <div class="col-xs-6" style="margin-bottom:5px ">
                         <a href="{% url 'kullanici:login' %}" class="btn btn-success " aria-pressed="true">GİRİŞ YAP </a>
                         </div>
                    </ul>
        </li>
        <li class="nav-item ">
               <ul class="navbar-nav mr-auto">
                        <div class="container" >
                        <div class="col-xs-6" style="margin-bottom:5px ">
                         <a href="{% url 'kullanici:register' %}" class="btn btn-primary " aria-pressed="true">ÜYE OL </a>
                         </div>
                  </div>  </ul>
            </li>
            {% endif %}

        <div class="nav-item " >
                <ul class="navbar-nav mr-auto">
                    <div class="container" >
                        <div class="col-xs-6" style="margin-bottom:5px ">
                        {% if request.user.is_authenticated %}
                         <a href ="{% url 'post:create' %}" class="btn btn-primary " aria-pressed="true">YAZI EKLE </a>
                        {% endif %}
                        </div>
                </div>
                </ul>
            </div>
    </ul> <form class="nav-item  navbar-left"  role="search"  method="GET" action="{% url "post:index" %}" >

      <div class="input-group">
                    <input class="form" type="text" name="q"  placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn  btn-outline-warning" type="submit" value="Ara">
                    </span>
                </div>
            </form></div>






</div>

          </div>
            </ul>




  </div> </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title%} €NGİNEER//{{ block.super }}{% endblock title%}
{% block body %}
    <div class="container">
         <div class="row justify-content-center" >
             <div class="col-lg-3 col-sm-4 col-xs-4 " >
        <div class="alert alert-danger" role="alert">
            {% if request.user.is_authenticated %}
                                 <div class="row" >

                                               HOŞGELDİNİZ    :{{ request.user.get_full_name }}

                                 {% else %}
                                                HOŞGELDİNİZ  :MİSAFİR
                                {% endif %}
        </div>                      </div>
  </div>
  </div>
</div>
<style>
.carousel-control-prev-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='darkblue' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
}

.carousel-control-next-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='darkblue' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
}
</style>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner border-danger">
    <div class="carousel-item active border-danger">

        <div class="container">
         <div class="row justify-content-center" >
             <div class=" col-xs-3" >
        <img src="{% static "bayrak.png"  %}" class="d-block w-100" alt="...">
             </div>
            </div>
         </div>
    </div>
    <div class="carousel-item">
        <div class="row justify-content-center" >
            <div class="col-md-6" >
      <img src="{% static "icon.png"  %}" class="d-block w-100" alt="...">
         </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon " aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{# <div class="container">#}
{#    <div class="row justify-content-center" >#}
{#    <img src={% static "icon.png"  %} width="400" height="400"  >#}
{#    </div>#}
{% endblock body %}

templates/info.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{{ info }}
{% endblock body %}

templates/messages.html
{% if messages %}

        {% for message in messages %}
            <div class="container">
         <div class="row justify-content-center" style="margin-bottom:5px">
             <div class="col-md-6 col-xs 3 " >
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
             </div>
</div>
</div>
    {% endfor %}

    {% endif %}



{#<div class="alert alert-success alert-dismissible fade show" role="alert">#}
{#                {{ message }}#}
{#                <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                <span aria-hidden="true">&times;</span>#}